[project]
name = "pytorch-detection-template"
description = "A project that does yolo & mmdetection && timm stuff"
authors = ["DawnMagnet<axccjqh@qq.com>"]
channels = ["conda-forge", "pytorch"]
platforms = ["win-64", "linux-64", "linux-aarch64"]

[dependencies]
python = "3.11.*"
pytorch = { version = ">=2.3", channel = "pytorch" }
torchvision = { version = "*", channel = "pytorch" }
ipykernel = "*"
setuptools = ">=75.3.0,<76"
wheel = ">=0.44.0,<0.45"
loguru = ">=0.7.2,<0.8"
rich = ">=13.9.3,<14"
icecream = ">=2.1.3,<3"

[feature.cuda118]
platforms = ["win-64", "linux-64"]
channels = ["nvidia", { channel = "pytorch", priority = -1 }]
system-requirements = { cuda = "11.8" }

[feature.cuda118.dependencies]
pytorch-cuda = { version = "11.8.*", channel = "pytorch" }

[feature.cuda124]
platforms = ["win-64", "linux-64"]
channels = ["nvidia", { channel = "pytorch", priority = -1 }]
system-requirements = { cuda = "12.4" }

[feature.cuda124.dependencies]
pytorch-cuda = { version = "12.4.*", channel = "pytorch" }

[feature.cpu]
platforms = ["win-64", "linux-64"]

[environments]
# cuda = ["cuda118"]
# cuda11 = ["cuda118"]
# cuda12 = ["cuda124"]
# cpu = ["cpu"]
default = ["cuda118"]

[pypi-options]
no-build-isolation = ["mmdet"]

[pypi-dependencies]
mmcv = ">=2.2.0, <3"
mmengine = ">=0.10.5, <0.11"
mmdet = { path = "./mmdet", editable = true }
timm = { path = "./timm", editable = true }
